### ISSUE TITLE
victure sc210

### ISSUE THREAD

**Issue by fkoteam** [cjj25/yi-hack-telnet-root#1]
Thank you for your work. I have victure sc210, based on YI IOT and RTS3903N
Firmware folder is home_r10m
I'm waiting for you solution to provide RTSP. I can test it on my cam.

Thank you again,

**Comment by code-explorer1234** [comment]
Thanks for leaving a comment, you gave me a little nudge to get it published into a repo.
I've updated the readme to include the link.

[https://github.com/cjj25/Yi-RTS3903N-RTSPServer](https://github.com/cjj25/Yi-RTS3903N-RTSPServer)

**Comment by fkoteam** [comment]
thank you! sadly (or not) I start today my holidays and I will not able to test until september. 
I have several comments:
 - My cam have the version 7.1.00.19A_201910181012 and I couldn't start telnet with your code, but it was avalaible following this way: https://github.com/rage2dev/YiOutdoor
 - I found binaries of the tapo c200 (same SoC and Linux Version) and I wanted to try it (or replacing whole firmware). Tapo cam has rtsp, http server, etc. Here some links: 
 https://georgeimmi.com/download/tapo/c200/
 https://drmnsamoliu.github.io/
 
Thank you for your work, I will update in weeks

**Comment by code-explorer1234** [comment]
Very strange to hear the telnet trick didn't work for you, which method did you try? I recommend using the WiFi version where you supply your own credentials.

I originally wanted to take the exact same path as you and I've even researched those same pages :)

Some of the libraries used in the RTSPServer project are actually from the source code released for the C200 and a few other cameras (the SDK). Replacing the whole firmware could be challenging due to the possible subtle differences in hardware, you'd be better using the binaries. 

I used some of the binaries such as the ISP tool from the C200 to discover how the streams were working and in the end decided that compiling something from the official SDK with the available header files was the approach for me.

Let  me know how you get on, I'm curious to see how the RTSPServer works for you - enjoy your holidays!

**Comment by code-explorer1234** [comment]
When you do get round to testing - please take a look at: https://github.com/cjj25/Yi-RTS3903N-RTSPServer/issues/1

**Comment by code-explorer1234** [comment]
>     * My cam have the version 7.1.00.19A_201910181012 and I couldn't start telnet with your code, but it was avalaible following this way: https://github.com/rage2dev/YiOutdoor
> 

@fkoteam  I've added this to the readme and given you a mention. It appears the older versions of the FW don't have the same init.sh script. Pls test the RTSPServer I posted previous to see if it works for you using the new payload.

**Comment by code-explorer1234** [comment]
@fkoteam, any update? I believe a user has posted confirmation that this camera appears to be working with the RTSPServer.

**Comment by fkoteam** [comment]
sorry, i'm the user 
I posted on the other project :)
it's working!

**Comment by code-explorer1234** [comment]
Fantastic news! I noticed you were interested in the 'iNite Night Vision Camera' binaries on "Hackaday".

If you're still interested in this, I do have a firmware dump. 

I've managed to get the official Realtek SDK 'turnkey' version to build an image for one of my cameras with the full Realtek stock experience (RTSP, web interface). 

The only issue is each hardware variation differs slightly, for example the U-Boot config needs to be mapped correctly for the smaller / larger size flash chips. It's handy to completely desolder the SPI flash and have an external ZIF adapter, hook up UART and keep testing.

While I'm happy I could get the full Realtek stock experience built, the potential legal copyright issues are stopping me as the binaries are precompiled. I've now switched my attention back to the original Yi firmware and I've spent time reverse engineering the circular buffer of the fshare_frame_buf.

**Comment by code-explorer1234** [comment]
Moving discussion to the RTSPServer repository.

**Comment by SergiJuan** [comment]
I have created an improved version of the original payload by @rage2dev for [YiOutdoor](https://github.com/rage2dev/YiOutdoor) cameras (firmware 7.1.00.19A+).  
My version consolidates the process into a single `config.sh` script that handles everything: from firmware backup and disabling cloud processes to launching telnet and RTSP servers.

I hope this can be useful for anyone still working with these cameras or looking for a simpler, more robust payload solution.

Feel free to check out my repository
https://github.com/SergiJuan/BetterYiOutdoor
